[api]
enabled = true
port = 54321

[db]
port = 54322

[functions.daily-summary]
verify_jwt = false

[functions.ki-lead-search]
verify_jwt = false

[functions.sale-price-scheduler]
verify_jwt = false

[functions.product-sync]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.notification-digest]
verify_jwt = false
