[api]
enabled = true
port = 54321

[db]
port = 54322

[functions.daily-summary]
verify_jwt = false

[functions.ki-lead-search]
verify_jwt = false

[functions.sale-price-scheduler]
verify_jwt = false
schedule = "1 0 * * *"
