-- Portfolio card view: canonical Founder OS records imported from the Drive master list.
CREATE TABLE IF NOT EXISTS portfolio_projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  area TEXT NOT NULL DEFAULT '',
  venture TEXT NOT NULL DEFAULT 'online_first',
  use_case TEXT NOT NULL DEFAULT '',
  audience TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'concept',
  visibility TEXT NOT NULL DEFAULT '',
  portfolio_relevance TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT '',
  tech_stack TEXT NOT NULL DEFAULT '',
  url TEXT,
  link_check TEXT NOT NULL DEFAULT '',
  next_step TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  is_archived BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION set_portfolio_projects_updated_at() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS portfolio_projects_updated_at ON portfolio_projects;
CREATE TRIGGER portfolio_projects_updated_at BEFORE UPDATE ON portfolio_projects FOR EACH ROW EXECUTE FUNCTION set_portfolio_projects_updated_at();

CREATE INDEX IF NOT EXISTS portfolio_projects_active_idx ON portfolio_projects(is_archived, venture, status);

ALTER TABLE portfolio_projects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS portfolio_projects_authenticated_read ON portfolio_projects;
CREATE POLICY portfolio_projects_authenticated_read ON portfolio_projects FOR SELECT TO authenticated USING (true);

INSERT INTO portfolio_projects (name, area, venture, use_case, audience, status, visibility, portfolio_relevance, role, tech_stack, url, link_check, next_step, notes, is_archived, updated_at)
VALUES
('SentinelLogic', 'App / SaaS', 'online_first', 'Branchenspezifisches CRM fuer Versicherungsmakler: Leads, Kunden, Angebote, Vertraege, Kommunikation und Statusverfolgung in einem Arbeitsfluss.', 'Versicherungsmakler, vertriebsgetriebene Dienstleister', 'development', 'Nur nach Freigabe / ggf. anonymisiert', 'A - starke Verkaufsreferenz', 'Konzept, Prozesslogik, Produktstrategie, Briefing, Prototyp-Bewertung', 'Vercel, Web-App, KI-gestuetzte Konzeption', NULL, 'Kein Link', 'Produktdemo, Screenshots und 1-seitige Case Study erstellen; echte Module klar benennen.', 'Art: CRM- und Kommunikationssystem | Prio alt/aktuell: Sehr hoch | Case Study: Ja | Offen: Live-Link, Screenshots, aktueller Status, genaue Funktionen, Kundenfreigabe', 'False', now()::timestamptz),
('ffm-leihhaus.de', 'Website', 'online_first', 'Lokale Vertrauens- und Lead-Website fuer Pfandkredit, Goldankauf und Schmuck/Uhren inklusive Rechner, Kontakt und WhatsApp.', 'Lokaler Dienstleister, Pfandleihhaus, Ankauf/Finanzservice', 'live', 'Oeffentlich', 'A - starke Verkaufsreferenz', 'Audit, Struktur, Text-/Section-Anpassungen, HTML/CSS-Unterstuetzung', 'Wordpress / Elementor, Lovable/HTML/CSS', 'https://ffm-leihhaus.de', 'Geprueft: live', 'Vorher/Nachher, Conversion-Elemente und Vertrauensbausteine als Case Study dokumentieren.', 'Art: Redesign / lokale Unternehmenswebsite | Prio alt/aktuell: Sehr hoch | Case Study: Ja | Offen: Finale Screenshots, genaue Ergebnisse, Kundenfreigabe', 'False', now()::timestamptz),
('Raimund Real Estate', 'Website', 'online_first', 'Unternehmenswebsite fuer Immobilien/Hausverwaltung mit serioeser Darstellung, Leistungsuebersicht und Kontaktanbahnung.', 'Immobilienunternehmen, Hausverwaltungen', 'live', 'Oeffentlich, falls freigegeben', 'A - starke Verkaufsreferenz', 'Webdesign, Umsetzung, Struktur, Projektabwicklung', 'WordPress / Elementor', 'https://raimundrealestate.de', 'Nicht oeffentlich verifiziert', 'Link/Freigabe klaeren und Projektumfang mit Ergebnis sauber nachtragen.', 'Art: Unternehmenswebsite / Immobilien | Prio alt/aktuell: Hoch | Case Study: Ja | Offen: Screenshots, genaue Leistungsbeschreibung, Freigabe, Ergebniskennzahlen', 'False', now()::timestamptz),
('Sprachbruecke FFM', 'Website', 'online_first', 'Lead-Website fuer Sprachunterricht mit mehrsprachiger Ansprache, Erstgespraech, Vertrauen und direkter Kontaktstrecke.', 'Coaches, Lehrer, Bildung, beratende Einzelunternehmer', 'live', 'Oeffentlich, falls freigegeben', 'A - starke Verkaufsreferenz', 'Webdesign, Umsetzung, Struktur, technische Einbindung', 'WordPress / Elementor, Calendly', 'https://sprachbruecke-ffm.de', 'Geprueft: live', 'Als Muster fuer Coaches/Berater-Paket nutzen; Screenshots und Buchungslogik dokumentieren.', 'Art: Mehrsprachige Website | Prio alt/aktuell: Hoch | Case Study: Ja | Offen: Screenshots, genaue Ziele, Ergebnis, Freigabe', 'False', now()::timestamptz),
('Blazed Outfitters', 'E-Commerce / Marke', 'blazed_outfitters', 'D2C Streetwear-Commerce mit Brand Story, Kollektionen, Drops, Lookbook, Produkten, Eventbezug und Community-Aufbau.', 'Eigene Brand, Streetwear, Creator-Commerce', 'active', 'Oeffentlich', 'A - starke Verkaufsreferenz', 'Brand-Aufbau, Shop, Kollektionen, Events, Affiliate, Marketingstrategie', 'WordPress / WooCommerce, Vercel, WordPress, Supabase, KI-gestuetzte Kampagnenplanung', 'https://blazedoutfitters.com', 'Geprueft: live', 'Shop/Brand getrennt auswerten: Umsatz, Kollektionen, Traffic, Event-Nutzen und Content-System.', 'Art: Streetwear-Brand und Onlineshop | Prio alt/aktuell: Sehr hoch | Case Study: Ja | Ursprungsziel: 8000 EUR / Monat | Ursprungs-Next-Step: 500 EUR Umsatz | Social-Kanaele IG, TikTok, Pinterest | Ursprungsnotiz: Aus alter Projektuebersicht uebernommen | Offen: Aktueller Shop-Link, Screenshots, Umsatzentwicklung, Top-Produkte', 'False', now()::timestamptz),
('Droplane', 'Plattform', 'blazed_outfitters', 'Creator-Marktplatz fuer limitierte Drops: Creator-Profile, Produktverkauf, Storytelling, Provision und Shopstruktur.', 'Creator, kleine Brands, Creator-Commerce', 'active', 'Oeffentlich, falls freigegeben', 'A - starke Verkaufsreferenz', 'Konzept, Plattformaufbau, Creator-Onboarding, Angebotssystem, Storytelling', 'WooCommerce, Dokan, WordPress / Elementor', 'https://droplane.eu', 'Geprueft: live', 'Plattformlogik, Creator-Onboarding und Einnahmemodell als Case Study visualisieren.', 'Art: Creator-Marktplatz | Prio alt/aktuell: Sehr hoch | Case Study: Ja | Ursprungs-Next-Step: 100 EUR Umsatz | Ursprungsnotiz: Aus alter Projektuebersicht uebernommen | Offen: Screenshots, aktive Creator, Verkaufszahlen, Prozessgrafik', 'False', now()::timestamptz),
('Brandary', 'B2B-Service / Website', 'brandary', 'B2B-Produktions- und Anfragewebsite fuer Corporate Merchandise, DTF, Lasergravur, Sublimation und White-Label.', 'B2B-Kunden, Vereine, Agenturen, Marken, Unternehmen', 'live', 'Teilweise', 'A - starke Verkaufsreferenz', 'Operating Model, Angebot, Website-/Systemkonzept, Produktstruktur', 'WordPress / Elementor, Supabase, Web-App (Admin)', 'https://bybrandary.de', 'Geprueft: live', 'B2B-Angebotspakete, Anfrageprozess und Beispielprojekte mit Preisen nachtragen.', 'Art: Druckservice / DTF / Sublimation / Laser | Prio alt/aktuell: Mittel | Case Study: Spaeter | Offen: Aktueller Status, Live-Link, Kundenbeispiele, Screenshots', 'False', now()::timestamptz),
('Dino''s Cut', 'Landingpage', 'online_first', 'Lokale Landingpage fuer einen Friseursalon/Barber mit schneller Positionierung, Kontakt und ggf. Terminlogik.', 'Lokale Dienstleister, Friseur/Beauty', 'live', 'Oeffentlich', 'B - Referenz nach Nachweis', 'Landingpage-Konzept / Umsetzung', 'Lovable / WordPress / Elementor', 'https://dinoscut.onlinefirst.eu', 'Nicht oeffentlich verifiziert', 'Erreichbarkeit, Screenshots und Freigabe klaeren; dann als einfache lokale Landingpage-Referenz nutzen.', 'Art: Friseur-/Barber-Landingpage | Prio alt/aktuell: Mittel | Case Study: Ja | Ursprungsnotiz: Aus alter Projektuebersicht uebernommen | Offen: Status, Link, Screenshot, Umfang, Freigabe', 'False', now()::timestamptz),
('Itaba', 'E-Commerce / POS', 'online_first', 'Commerce-/POS-Konzept fuer japanische Artikel mit Shop, Lager-/Filiallogik und Kassensystem-Anbindung.', 'Einzelhandel, Spezialhandel, E-Commerce mit Filiale', 'development', 'Zu klaeren', 'B - Referenz nach Umsetzung', 'Angebot, technische Konzeption, Systemplanung', 'WooCommerce, SDS Kassensystem Neo 365, POS', NULL, 'Kein Link', 'Entscheiden, ob Angebot, Prototyp oder aktives Projekt; Link/Screenshots nachtragen.', 'Art: Shop mit Lager-/Filiallogik | Prio alt/aktuell: Mittel | Case Study: Moeglich | Ursprungsziel: bis Ende Februar 2026 | Ursprungsnotiz: Aus alter Projektuebersicht uebernommen | Offen: Umsetzungsstatus, Link, Screenshots, Kunde/Freigabe', 'False', now()::timestamptz),
('Hochzeitsplaner / Startflow', 'Digitalprodukt / App-Konzept', 'online_first', 'Digitalprodukt fuer Hochzeitsplanung mit Budget, Aufgaben, Anbieterbriefings, Statusueberblick und mehrsprachigem Potenzial.', 'Digitale Produkte, Etsy/Digistore, Paare', 'concept', 'Eigene Referenz', 'B - Produktchance', 'Produktanalyse, Positionierung, MVP-/Startflow-Konzept', 'KI, No-Code/Web-App moeglich, Excel', NULL, 'Kein Link', 'Verkaufsfertigen MVP, Produktbilder, Etsy-Listing und Proof-of-Value finalisieren.', 'Art: Planungsprodukt / MVP | Prio alt/aktuell: Mittel | Case Study: Spaeter | Offen: Prototyp-Link, Zielgruppe, Screenshots, aktueller Stand', 'False', now()::timestamptz),
('KI Funding Manager fuer Blazed', 'KI-Agent', 'blazed_outfitters', 'KI-Agent zur strukturierten Suche nach Finanzierung, Foerdermitteln, Banken, Investoren und Outreach-Optionen.', 'Eigene Finanzierung, kleine Unternehmen', 'concept', 'Intern', 'C - intern / spaeter', 'Agentenidee, Finanzierungsstrategie, Zieldefinition', 'KI-Agenten, Recherche, CRM/Outreach-Automation', NULL, 'Kein Link', 'Nur als internes System weiterfuehren; erst nach Proof of Concept portfoliofaehig.', 'Art: Finanzierungs- und Fundraising-Agent | Prio alt/aktuell: Mittel | Case Study: Nein / intern | Offen: Workflow, Datenquellen, rechtliche Grenzen, Proof of Concept', 'False', now()::timestamptz),
('KI mit Startbudget', 'KI-Agent / Experiment', 'online_first', 'Experimenteller KI-Agent mit kleinem Budget, klaren Regeln und Wachstumshypothese.', 'Experiment, Content, KI-Systeme', 'concept', 'Intern / Storytelling', 'C - intern / spaeter', 'Konzept, Architekturgedanken, Experimentdesign', 'KI-Agenten, Wallet/API, Automatisierung', NULL, 'Kein Link', 'Sicherheitsregeln, Budgetgrenzen und messbares MVP definieren.', 'Art: Autonomes Business-Experiment | Prio alt/aktuell: Niedrig | Case Study: Nein / spaeter | Offen: Regeln, MVP, Kostenrahmen, Ergebnisnachweis', 'False', now()::timestamptz),
('Pokemon-/LEGO-Agent', 'KI-Agent / Marktanalyse', 'online_first', 'KI-Rechercheagent fuer Sammlerprodukte, Preisentwicklung, Signale und Kaufgelegenheiten.', 'Nebenprojekt, Marktanalyse, Sammlerprodukte', 'concept', 'Intern', 'C - intern / spaeter', 'Brainstorming, Agentenidee, Entwicklungsauftrag', 'KI-Recherche, Scraping/API, Preisbeobachtung', NULL, 'Kein Link', 'Zurueckstellen, bis Hauptfokus stabil laeuft.', 'Art: Sammlerprodukt-Recherche | Prio alt/aktuell: Niedrig | Case Study: Nein | Offen: Datenquellen, Budget, Regeln, Ergebnisziel', 'False', now()::timestamptz),
('Online First', 'Agentur / Dachmarke', 'online_first', 'Dachmarke fuer Webdesign, E-Commerce, Landingpages und digitale Systeme fuer kleine Unternehmen.', 'KMU, lokale Unternehmen, Coaches, Shops', 'active', 'Oeffentlich', 'A - strategische Dachmarke', 'Positionierung, Angebote, Akquise, Projektumsetzung', 'WordPress, WooCommerce, Lovable, KI-gestuetzte Umsetzung', NULL, 'Kein Link', '6 beste Referenzen auswaehlen und Angebotspakete mit klaren Preisen bauen.', 'Art: Webdesign- und E-Commerce-Angebot | Prio alt/aktuell: Sehr hoch | Case Study: Nein / Dachmarke | Ursprungs-Next-Step: Sales Prozess aufstellen | Ursprungsnotiz: Aus alter Projektuebersicht uebernommen | Offen: Finale Positionierung, Website-Link, Angebotsstruktur, Referenzen', 'False', now()::timestamptz),
('Latinstreetbrand', 'Website / Business-Idee', 'online_first', 'Aeltere Fashion-/Brand-Idee mit Latin-Urban-Fokus.', 'Eigene Brand / Fashion', 'archived', 'Zu klaeren', 'Archiv', 'Zu ergaenzen', 'Zu ergaenzen', NULL, 'Kein Link', 'Archivieren, wenn kein aktueller Umsatz, Link oder strategischer Bezug vorhanden ist.', 'Art: Latin Urban Fashion | 5 % | Prio alt/aktuell: Mittel | Case Study: Moeglich | Ursprungsnotiz: Altes abgeschlossenes Fashion-/Brand-Projekt | Offen: Aktueller Status, Link/Screenshots, Ergebnis, Relevanz fuer Portfolio', 'True', now()::timestamptz),
('Moda Natura', 'Website / Business-Idee', 'online_first', 'Kundenprojekt fuer Accessoires; potenziell E-Commerce-/Brand-Referenz, falls live und sauber belegt.', 'Accessoires, kleiner Shop, Kundenprojekt', 'archived', 'Oeffentlich', 'B - Referenz nach Nachweis', 'Zu ergaenzen', 'Wordpress / Elementor', 'https://modanatura.de', 'Nicht oeffentlich verifiziert', 'Erreichbarkeit, Freigabe und Ergebnis pruefen.', 'Art: Kundenprojekt fuer Accessoires | 5 % | Prio alt/aktuell: Mittel | Case Study: Spaeter | Ursprungsnotiz: Altes abgeschlossenes Kundenprojekt | Offen: Aktueller Status, Link/Screenshots, Ergebnis, Relevanz fuer Portfolio', 'True', now()::timestamptz),
('PerreoZone', 'Website / Business-Idee', 'online_first', 'Aelteres Marketing-/Konzeptprojekt mit unklarem heutigen Nutzen.', 'Marketing-Konzept, Altbestand', 'concept', 'Zu klaeren', 'Archiv', 'Zu ergaenzen', 'Zu ergaenzen', NULL, 'Kein Link', 'Archivieren, wenn kein aktiver Nutzen oder Proof vorhanden ist.', 'Art: Austausch gegen Marketing-Konzept | Prio alt/aktuell: Sehr hoch | Case Study: Nein / intern | Ursprungsziel: bis Ende Oktober 2025 | Ursprungsnotiz: Status heute pruefen | Offen: Aktueller Status, Link/Screenshots, Ergebnis, Relevanz fuer Portfolio', 'False', now()::timestamptz),
('MotivoWear', 'Website / Business-Idee', 'blazed_outfitters', 'Motivations-Fashion-Konzept; auf Droplane sichtbar anschlussfaehig, aber noch nicht als eigene Referenz belastbar.', 'Fashion, Droplane Creator/Brand', 'concept', 'Zu klaeren', 'B - spaeter pruefen', 'Zu ergaenzen', 'Zu ergaenzen', NULL, 'Kein Link', 'Nur weiterfuehren, wenn es als Creator-Drop auf Droplane konkret verkauft wird.', 'Art: Fashion fuer Motivation | Prio alt/aktuell: Hoch | Case Study: Nein / intern | Ursprungsnotiz: Alte offene Fashion-Idee | Offen: Aktueller Status, Link/Screenshots, Ergebnis, Relevanz fuer Portfolio', 'False', now()::timestamptz),
('Lineva', 'Website / Business-Idee', 'online_first', 'Produktidee fuer Sprueche/Wandbilder.', 'Printprodukt, Deko, Etsy', 'concept', 'Zu klaeren', 'Archiv', 'Zu ergaenzen', 'Zu ergaenzen', NULL, 'Kein Link', 'Archivieren oder spaeter als digitales Print-on-Demand-Experiment neu bewerten.', 'Art: Sprueche Wandbilder | Prio alt/aktuell: Hoch | Case Study: Nein / intern | Ursprungsnotiz: Alte offene Produktidee | Offen: Aktueller Status, Link/Screenshots, Ergebnis, Relevanz fuer Portfolio', 'False', now()::timestamptz),
('DomiMoves', 'Plattform / Creator von Droplane', 'blazed_outfitters', 'Creator-Drop innerhalb Droplane mit Dance/Latin-Story und Fashion-Produkten.', 'Creator-Commerce, Droplane', 'active', 'Zu klaeren', 'B - Referenz nach Nachweis', 'Zu ergaenzen', 'Zu ergaenzen', NULL, 'Kein Link', 'Creator-Seite, Produkte, Umsatz/Status und Screenshots nachtragen.', 'Art: Fashion 7,5 % | Prio alt/aktuell: Sehr hoch | Case Study: Nein / intern | Ursprungs-Next-Step: 100 EUR Umsatz / Monat | Ursprungsnotiz: Creator-Projekt innerhalb Droplane | Offen: Aktueller Status, Link/Screenshots, Ergebnis, Relevanz fuer Portfolio', 'False', now()::timestamptz),
('SpaceFarmer', 'Plattform / Creator von Droplane', 'blazed_outfitters', 'Creator-Brand innerhalb Droplane mit mehreren Linien, Storytelling und Onboarding-Prozess.', 'Creator-Commerce, Droplane, Kundenprojekt', 'active', 'Zu klaeren', 'B - Referenz nach Nachweis', 'Zu ergaenzen', 'Zu ergaenzen', NULL, 'Kein Link', 'Projektverlauf, Zahlungen, fertige Linien und Launch-Status sauber dokumentieren.', 'Art: Fashion 7,5 % | Prio alt/aktuell: Sehr hoch | Case Study: Nein / intern | Ursprungsziel: bis Ende November 2025 | Ursprungsnotiz: Creator-Projekt innerhalb Droplane | Offen: Aktueller Status, Link/Screenshots, Ergebnis, Relevanz fuer Portfolio', 'False', now()::timestamptz),
('Divanlot', 'Plattform / Creator von Droplane', 'blazed_outfitters', 'Aeltere Creator-/Fashion-Idee innerhalb Droplane.', 'Creator-Commerce, Altbestand', 'concept', 'Zu klaeren', 'Archiv', 'Zu ergaenzen', 'Zu ergaenzen', NULL, 'Kein Link', 'Archivieren, bis klarer Creator, Produkt oder Umsatzchance vorhanden ist.', 'Art: Fashion 7,5 % | Prio alt/aktuell: Hoch | Case Study: Nein / intern | Ursprungsziel: bis Ende 2025 | Ursprungsnotiz: Creator-/Fashion-Projekt innerhalb Droplane | Offen: Aktueller Status, Link/Screenshots, Ergebnis, Relevanz fuer Portfolio', 'False', now()::timestamptz),
('Carlos Guitarrist', 'Zu klaeren', 'online_first', 'Kuenstler-Portfolio mit Biography, Media, Audio/Videos, Reviews, Kursen und Kontaktanfrage.', 'Kuenstler, Musiker, Personal Brand', 'live', 'Zu klaeren', 'A - starke Verkaufsreferenz', 'Leistung/Rolle ergaenzen', 'Wordpress / Elementor', 'https://carlosrestrepoguitarist.com', 'Geprueft: live', 'Projektziel, Rolle, Umfang und Screenshots nachtragen; als Personal-Brand-Referenz nutzen.', '', 'False', now()::timestamptz),
('Founder OS', '', 'online_first', '', '', 'development', '', '', '', '', NULL, '', '', '', 'False', now()::timestamptz),
('Memory Spiel', '', 'online_first', '', '', 'concept', '', '', '', '', NULL, '', '', '', 'False', now()::timestamptz),
('Kleiderschrank App', '', 'online_first', '', '', 'concept', '', '', '', '', NULL, '', '', '', 'False', now()::timestamptz)
ON CONFLICT DO NOTHING;
